## Setup

In [1]:
from googleapiclient.discovery import build
import json
import re
from collections import Counter
from datetime import datetime
from googleapiclient.discovery import build
import pandas as pd
import numpy as np
import glob
import os

In [2]:
with open ("../performative.txt", "r") as f:
    lines = f.readlines()
    API_KEY = lines[2].strip()
    
yt = build("youtube", "v3", developerKey=API_KEY)

### Static/Maps

In [3]:
GENRE_MAP = {
    "1":  "Film & Animation",
    "2":  "Autos & Vehicles",
    "10": "Music",
    "15": "Pets & Animals",
    "17": "Sports",
    "19": "Travel & Events",
    "20": "Gaming",
    "22": "People & Blogs",
    "23": "Comedy",
    "24": "Entertainment",
    "25": "News & Politics",
    "26": "Howto & Style",
    "27": "Education",
    "28": "Science & Technology",
    "29": "Nonprofits & Activism",
}

In [4]:
QUERIES = [
    "video essay film analysis",
    "philosophy explained documentary",
    "internet culture deep dive",
    "history documentary essay channel",
    "game design analysis",
]
MAX_PER_QUERY = 50  # how many channels to collect per keyword/phrase

## Scripts

In [5]:
def search_channels_queries(query, max_results, seen):
    collected = []
    next_page = None

    while len(collected) < max_results:
        resp = yt.search().list(
            part="snippet",
            q = query, 
            type="channel",
            relevanceLanguage = "en",
            maxResults=50,
            pageToken = next_page,
        ).execute()

        for item in resp["items"]:
            cid = item["snippet"]["channelId"]
            if cid not in seen:
                seen.add(cid)
                collected.append({
                    "channel_id":   item["snippet"]["channelId"],
                    "channel_name": item["snippet"]["title"],
                })
            if len(collected) >= max_results:
                break
        
        next_page = resp.get("nextPageToken")
        if not next_page:
            break
    return collected

In [12]:
def search_channels_playlist(playlist_id, seen):
    collected = []
    next_page = None

    while True:
        resp = yt.playlistItems().list(
            part="snippet",
            playlistId=playlist_id,
            maxResults=50,
            pageToken=next_page,
        ).execute()

        for item in resp["items"]:
            cid = item["snippet"].get("videoOwnerChannelId")  # dict[key] raises a KeyError when the key is missing. dict.get(key) gracefully returns None. verify?
            if cid not in seen:
                seen.add(cid)
                collected.append({
                    "channel_id":   cid,
                    "channel_name": item["snippet"].get("videoOwnerChannelTitle"),
                })
        
        next_page = resp.get("nextPageToken")
        if not next_page:
            break
    return collected

## Running

In [13]:
all_channels = []
seen = set()

for query in QUERIES:
    print(f"Searching: {query}")
    results = search_channels_queries(query, MAX_PER_QUERY, seen)
    print(f" got {len(results)} channels")
    all_channels.extend(results)

with open("../data/processed/ve_channels/ve_channels_queries.json", "r") as f:
    existing = json.load(f)
combined = existing + all_channels
with open("../data/processed/ve_channels_queries.json", "w") as f:
    json.dump(all_channels, f, indent=2)

Searching: video essay film analysis
 got 50 channels
Searching: philosophy explained documentary
 got 24 channels
Searching: internet culture deep dive
 got 50 channels
Searching: history documentary essay channel
 got 50 channels
Searching: game design analysis
 got 50 channels

In [14]:
seen = set()

results = search_channels_playlist("PLXz6Pf8rae1mIGQ8IdpggWP2RmW1wmXsa", seen)

with open("../data/processed/ve_channels/ve_channels_playlist.json", "w") as f:
    json.dump(results, f, indent=2)

In [15]:
results2 = search_channels_playlist("PLbOF9TQmQrNgWHaLCPaE81l4hEL-2Rrjf", set())

with open("../data/processed/ve_channels/ve_channels_playlist_2.json", "w") as f:
    json.dump(results2, f, indent=2)

## Viewing Data

In [16]:
with open("../data/processed/ve_channels/ve_channels_queries.json", "r") as f:
    data_queries = json.load(f)

In [17]:
df_queries = pd.DataFrame(data_queries)
df_queries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 225 entries, 0 to 224
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   channel_id    225 non-null    object
 1   channel_name  225 non-null    object
dtypes: object(2)
memory usage: 3.6+ KB

In [18]:
with open("../data/processed/ve_channels/ve_channels_playlist.json", "r") as f:
    data_playlist = json.load(f)

In [19]:
df_playlist = pd.DataFrame(data_playlist)
df_playlist.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107 entries, 0 to 106
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   channel_id    106 non-null    object
 1   channel_name  106 non-null    object
dtypes: object(2)
memory usage: 1.8+ KB

In [20]:
with open("../data/processed/ve_channels/ve_channels_playlist_2.json", "r") as f:
    data_playlist2 = json.load(f)

In [21]:
df_playlist2 = pd.DataFrame(data_playlist2)
df_playlist2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   channel_id    23 non-null     object
 1   channel_name  23 non-null     object
dtypes: object(2)
memory usage: 500.0+ bytes

## Cleaning Data

In [39]:
df = pd.concat([df_queries, df_playlist, df_playlist2])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 355 entries, 0 to 22
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   channel_id    354 non-null    object
 1   channel_name  354 non-null    object
dtypes: object(2)
memory usage: 8.3+ KB

In [40]:
df = df.drop_duplicates(subset="channel_id").reset_index(drop=True)

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 341 entries, 0 to 340
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   channel_id    340 non-null    object
 1   channel_name  340 non-null    object
dtypes: object(2)
memory usage: 5.5+ KB

In [42]:
rows_to_add = [{"channel_id": "UCD6TPU-PvTMvqgzC_AM7_uA", "channel_name": "The People Profiles"},
               {"channel_id": "UC1DTYW241WD64ah5BFWn4JA", "channel_name": "Sam O'Nella Academy"},]

In [43]:
df[df["channel_id"] == "UC1DTYW241WD64ah5BFWn4JA"]

Empty DataFrame
Columns: [channel_id, channel_name]
Index: []

In [44]:
df.iloc[50:100]

                  channel_id                                  channel_name
50  UCwbDCAPugfe1KrbCZ9F0VPw                            Philosophy Origins
51  UCTNKkxZDNDjVGcibLg1D6Ww                            Philosophy Matters
52  UCCfI-j18jSgT45svMcofILw                  Documentaries and Philosophy
53  UCp1mRTkVlqDnxz_9S0YD9YQ                         Philosophies for Life
54  UCIuCDa-yyDddjzVfu6WMiNQ                      Philosophy Documentaries
55  UCBz-uxcltpYVrL9On42z2qQ                             Philosophy Corner
56  UCVvux6AY30Iqe7bxxcjL2LA                              Sam's Philosophy
57  UCXRNtFb3LCHxaV4u0XlrAvQ                     Philosophy Sleeping Story
58  UC7IcJI8PUf5Z3zKxnZvTBog                            The School of Life
59  UCWTc-B9-9j5Tykq7ou4tL3Q                            Philosophy Decoded
60  UC4-_zXv3UJ3JQQlPpgyt_yA                             Film & Philosophy
61  UCNumg0oUUDu7RTafz_jDPbg                         Feeling Philosophical
62  UCSS_4ZD4lk4VDtaWTM0Q67w                           The Film Philosophy
63  UCa3CO3-AoZeHKG-dX21ooGQ  Philosophical Library - From Socrates to Now
64  UCBbFUp-9BBItN622O4Itiag                 Philosophy for a Small Planet
65  UCwN-cNbUD-06p299P5bKvZw            Philosophy: Docs, Series & Clashes
66  UCvHUC4R-dEJyD9W5fskzeBA                           Philosophy Insights
67  UCy4ogZ3g2gQLKwBbEMgaFfA                              Philosophy facts
68  UCisWUR5UCMcxz_4zT6mI3kA                           FilmComicsExplained
69  UC8CCk3ehhTQcbTPew-znYXA                         Leadership Philosophy
70  UCpWuAUrnBETrn49zEyHOhRg                             Philosophy of You
71  UCePDFpCr78_qmVtpoB1Axaw                           Great Art Explained
72  UC9thvKQUy3u--Z-fKC_vNHg            Physics and Philosophy with Naveed
73  UCYaZ31-kPwFpoLjDkO6904w                     Philosophy in a Nutshell
74  UCl8YscarysgHySZ8N1ynPCQ                                    Philosophy
75  UCYKyJ9iXg06Zu4wgmO_yXvA                                DJW Philosophy
76  UCbgmHSpunb0aPBqsxBWbUew                               Reel Philosophy
77  UC0gHbWz7OyEa-kz429hzx1Q                           Sleeping Philosophy
78  UCdYvUL5xKB7UsA5X1B5Lntw                            The Philosophy Doc
79  UCu5zC3kGbqcQ2ydfdEJw7lQ                              Learn and Reform
80  UCAIS3ntrjs9FNks7mJvDh-g                              Art & Philosophy
81  UC0cd_-e49hZpWLH3UIwoWRA                       Professor Dave Explains
82  UCQx5EM5m75XXaV3wYF9hBrw                          Psychotic Philosophy
83  UCVuuvj_ItrMNwh1Cg52gRlw                              Movie Philosophy
84  UCPr7glNCExHHXvFeHN6j7fQ            Marcus Tylor - Profound Philosophy
85  UCnwUjPK7dXety-AJ4fNw_RQ                           The Paint Explainer
86  UCUC928ZJ3xrFftj9vrLColg                          Philosophy Film Club
87  UCxndIUbRpoD0B8LCOXg3v6w                           The Philosophy Path
88  UCxA3ya0zJZbadABlr2AG4UA                              Desi Philosopher
89  UCmXWDmYfCjocfwoMHrm3D6Q                            Philosophy Connect
90  UCuonEX9nR9zx8BPXeYs9Smg         Verse and Vision: Films & Philosophy
91  UCb-ym8XJNkb-OALSK7iZf8g                         The Philosophy of Art
92  UCWzMfNA9FO8fMidxK3oMnQQ                            SacredU Philosophy
93  UCxe8hBN_jtfosMcCdlf6yyg                      The Northern Philosopher
94  UCIKYhEe9O9aqukXgPfudC0A                             Ginema Philosophy
95  UC11aHtNnc5bEPLI4jf6mnYg                            Predictive History
96  UCX6b17PVsYBQ0ip5gyeme-Q                                   CrashCourse
97  UC-aAYolBbmzGLoG0l2c6kaQ                               Documentary XXL
98  UCjGD79rjiYpVLnWKmadtShw                            Philosophical Era
99  UCltydpU9pGNSn4ZR8Nt5xzA                                    Unlearning

In [45]:
df.iloc[100:150]

                   channel_id                         channel_name
100  UCt3JiNkefsfbA2N4SgEkoiQ                       Visual Venture
101  UCnoYaHN1zDCD-vcNXdwF-8g                            Deep Dive
102  UCY6DpwQetygtye7GM1zVHmw                          tiffanyferg
103  UCGKUQte8RBCNnI_OYpckErg                        Hannah Alonzo
104  UCmdRI2gLXb8hp2cNcvuj0MQ                             Danielle
105  UCvCzQh2gf1zantUDmvKP_8A                      Viral Deep Dive
106  UCa7Niyr46r2QHVdhIB_-_3A                 TheDigitalRabbitHole
107  UCSUwFKuCzI42rOaIEIFM7Xw             Based Internet Mysteries
108  UC6QuQhhRicNwoxtuFzq_Qdw                      Doomscroll Dive
109  UCDpOXvDm7WStFeSDRxnzdqA                       Just Happen It
110  UCM9nWkBMO5w8K_jRA2WKTvg    The Web Browser Deep Dive Podcast
111  UCDNKxqbPtQ8_26GYEKy728g                     Internet Archive
112  UC0sSz9mEtrUZIcdGnCgAX-g             SrangeNet Investigations
113  UCMA7L1oRCozJaehbDFF6p_Q                           DT is Back
114  UCNTH6eHuXQL4NhGKkkI1C3w                        Venture deep™
115  UCGGbBUmAf4KmVuEb2TWu-xQ                    RabbitHoleStories
116  UCj8l_GB-x16Rd12uYAXJXkg                           FameGlitch
117  UCYIzsED8GuZ_q-MqcrJ0k-w                 Deep Dive with Saeed
118  UC_QhSdt-NT8Il4I49hkASGA                 Deep Dive Commentary
119  UC_QHUVVZ-61WjpC1_yZPjlQ                   The Release Window
120  UC9a2qR5j0tCp_c8zYyukulg                         Holden Smith
121  UC9ofQrNmra_847yJHUdHhiw                       SideEyeCentral
122  UCmLt1q6CVQqGi4t79E1BofA                           Variant313
123  UCMzjGdX2Vm7eUWWKxG-6wqQ                            Brain Rot
124  UCRkWTpbN3lREbdIqTRtB-Qw                           Live Logic
125  UCoqMDyDUcAXzGy273McJVuw                             The Hook
126  UCw3lIVukmwtOe6xJSFGHrBA             Internet Mysteries Vault
127  UC5KPd_Ze3pZkQ1HmkqQNDXA  Fandabi Deepdive with Tom Langhorne
128  UC3nYuhdtx3c-oyzFYj2sh2w                      Brainrot Buffet
129  UCpA0TubK9f8JFTi__rKZAaQ                      Deep Dive Vault
130  UC0gevDBuoo_vG74V4UNnPWw                      Ranking Mode ON
131  UCOhd4drfOy45ZmLecs0QhBQ                          Deep Trends
132  UCpzveoPAXCdDtavM02Vz5lg                             Tea Talk
133  UCNofTZGY1LuGlppDNys_ThQ                                Jonii
134  UCX1vm9taXpWotgYC3vZN9rQ                            Deep Dive
135  UCQleXyEWpn5LTEufJjo7GmA                        Culture Clash
136  UCUyaW24wDoDU6wAmsHmI01A                           Deep Dives
137  UCP04miW14zs0ilKrnksgzCg                            Chrominds
138  UC8WHN5tArP4zgWYB-uwJR5Q                 Celebrities Debunked
139  UCiObh4z9hNBrKwBMWpCRPlA                             Geranium
140  UCHKxZukFlCOs6MUXwSD6mHQ                         Kamden Talks
141  UC2bCEU0uur3FLqVv5m17FYg                                Rocky
142  UC18hwezPEHhmgBw9G2VZ9Ow                       MostViral hook
143  UCWIeD6Ew1y-wVHgG1Rki4Ug                        Mosh Explains
144  UCa1Ux2L-OLxdvi6hODAiH4A   The Deep Dive: Constructed Reality
145  UCbVnu3mSZNKoAX6SPxeQiMQ                          BlockBanter
146  UCZFG7duqRGDxuoCtAkRFoZQ                          skibidi age
147  UCgL80hNlrKLAcsAbDSRI-8w                    Pee pod cove life
148  UCTB4b_HXsA-O_JTfKGCWKew                           BeefleePut
149  UCbrtGrZwUQH4_PP9cOGSC-A                    Metalbeard Mayhem

In [46]:
rows_to_drop = [11, 12, 18, 36, 50, 51, 52, 54,
                 56, 57, 59, 60, 62, 63, 65, 66, 67,
                 69, 70, 72, 73, 74, 77, 78, 79, 80, 82, 
                 83, 84, 86, 87, 88, 89, 90, 91, 92, 94, 97,
                 98, 105, 106, 107, 108, 109, 110, 111, 112,
                 113, 114, 115, 116, 117, 118, 119, 121, 122,
                 123, 124, 125, 126, 127, 128, 129, 130, 131,
                 132, 134, 136, 137, 138, 139, 141, 142, 143,
                 144, 145, 146, 148, 149, 172, 178, 186, 187,
                 188, 189, 191, 198, 216, 224]

In [47]:
df.iloc[150:200]

                   channel_id                            channel_name
150  UCTv4kbT56qnD3iL-o-pfEiw                      Historical Amnesia
151  UCkS_HP3m9NXOgswVAKbMeJQ                              Then & Now
152  UCrx2zrPjhGRi9TwszZiLwEg                                 Horses
153  UCT6Y5JJPKe_JDMivpKgVXew                   Fall of Civilizations
154  UCmDTX6KHkuPS_L63lyK2BbQ                    History of Elections
155  UC_3pplzbKMZsP5zBH_6SVJQ     Chris Chan: A Comprehensive History
156  UCz8BwZBpbZzHH7xQrvt0qRQ                         DJBoHistory Tv
157  UCLXo7UDZvByw2ixzpQCufnA                                     Vox
158  UC-R24vaD9ZoucOlhYkIZtDw  The Decline and fall of British Sci-Fi
159  UCmGSJVG3mCRXVOP4yZrU1Dw                           Johnny Harris
160  UC-SrCCzkGq0wmSAuRs7EBFg                           Miniminuteman
161  UCIeW-5N9YSCcERWYtz20-8g                       History Clarified
162  UC6BLQ4Po0euDOZq9gUgkWAQ                          Forrest Valkai
163  UCL5kBJmBUVFLYBDiSiK1VDw                     The House of Tabula
164  UC_iUeUzozCHEReJ-shKcCYA                      Internet Anarchist
165  UCSWdtggn4s1uG92diBbtZng                             Frankie Fey
166  UCVo63lbKHjC04KqYhwSZ_Pg                             Defunctland
167  UCtUbO6rBht0daVIOGML3c8w                          Summoning Salt
168  UC3cpN6gcJQqcCM6mxRUo_dA                               Wendigoon
169  UCHyptQKq5lxkSHlyOk6bubA                                  SIRIUS
170  UCUsJAAPcT5T_hoSXdNfOP4Q   History Tea Time with Lindsay Holiday
171  UCWTFGPpNQ0Ms6afXhaWDiRw                          Now You See It
172  UC6P7hs4XJxPI8BJjeR5Nq5w                             TTA History
173  UCMX31RavkfUHJvw03RbUZnA                            Nick Crowley
174  UCO01ytfzgXYy4glnPJm4PPQ                              Matt Walsh
175  UCODHrzPMGbNv67e84WDZhQQ                                    fern
176  UCt-HTfaCUz8QIoknqyXKYiw                                 Wirtual
177  UCl9ocQSoD3QO5n1gI1I8j_Q                          Faze 1 History
178  UC4AnCOQTwhbGQziVqod7U9w                    WILD SIDE OF HISTORY
179  UCn8zNIfYAQNdrFRrr8oibKw                                    VICE
180  UCCZqogFSVe-qLfgVk9-AXfw                        ancient mariner
181  UCpFFItkfZz1qz5PpHpqzYBw                                   Nexpo
182  UCC0XWOgSBcwNstXbPX2cbpg                       Historical Africa
183  UC1U__SxUBFAn14nU4ERp6rg             Theoretical YouTube Channel
184  UCI9DUIgtRGHNH_HmSTcfUbA                         The Closer Look
185  UCwxnmj47urz63D3i9kPZBqg             Kienna Powell: Film and tv
186  UCNlTe1ENsyQyT_nXkjyzkCA                         Chronicle Quest
187  UCRbYtWqY7rBRa51gR8UCy-Q                          The Historians
188  UCkET1ocGd3WgIbk3WlZjj3A             Chat History Grade 10,11,12
189  UC9RivepmyifkUIv-phSy9pA                       The Film Basement
190  UC3d64X0YAFQHxAOXN49B10w          matttt - comic & manga history
191  UCdw48DhUASSjtLYSzVK8eTw                     Hawai‘i History Day
192  UCwpJ7oBJ5-ArLujm3ljWHzQ                              Essay Nerd
193  UCVdDUN69YsAXPxh2y71sMtQ                 I Finished A Video Game
194  UCnkuf3XFebDum87YSx5BVyg                                  Catman
195  UCQgoGGIqDt4Kpi4ysw4w7mg                    Benjamin Thorvaldsen
196  UCiH828EtgQjTyNIMH6YiOSw                         Channel Awesome
197  UCf_GOjxPIdOaf47gOXw6LrA                     Birth.Movies.Death.
198  UC5vmijPM5bUABtEROLoYGhA                      The Lost Blueprint
199  UC-mP1nlk0qOutA08zuQHORA                             Patrick Cc:

In [48]:
df.iloc[200:250]

                   channel_id                           channel_name
200  UCNaAppb_FDGLH3vLnUcY3Pg                           Design Frame
201  UCO9k7tfA_H9FZ_sDi6bNFXw       Games Every Designer Should Play
202  UCZMF14eNxvuReRTceX_mbqQ                  The Game Overanalyser
203  UCE5FiTkmvVHzVScukla75uw                    Game Designer Plays
204  UCtZMWqGbT2UDdw1gGqVEpRg                 Let's Talk Game Design
205  UCpkmLZ83NKt6FTN4kKUgdyg                               yakkocmn
206  UCv1DvRY5PyHHt3KN9ghunuw     Masahiro Sakurai on Creating Games
207  UCJr7DrVt9FEQjys6mWP8Y1w                          Designing For
208  UCSdma21fnJzgmPodhC9SJ3g                             NakeyJakey
209  UC1_U9dYmPupJTQUz4N3UBGw                         Out Of Nickels
210  UCwRmhfhqCMKcpQQhWuY3xFw                                 Snulch
211  UCVeSxsrvjoX4TCKg65Y0rUw                              Game Arts
212  UCJPQyAGAbIcXZXfM01oOPOA                            Game Wisdom
213  UCGmxNOQoWHzUzYrEeLRpxzQ                   Game Design Thinking
214  UCFhJb1xEmmk-iS8bSNNvsjA                    Game Audio Learning
215  UCAb4NMt-Bogt2J_fDG-Bm5Q                  Light and Game Design
216  UCHnLnlRg2upym9DFAVLj9Wg                    Selasar Game Design
217  UC9QThRmFFvh30IUj6d-bBnQ                 Alan | JungoGymStudios
218  UCIvHShVTBwUtBBpX49nLMew                           Patrick Rose
219  UC1gpfeM0eRK2IhdQ8uIyBcQ                           Homa Academy
220  UCeg61WV0Ryf9ySgy3PsOsmw                            scott kabel
221  UCf2myWcyYEgKjo3XJPQIrdw                             NOBL Games
222  UClnLJ77n2Cnf-N9QJX9fUeQ  CareLevelZero (A Game Designer Plays)
223  UCrIZMp3lvblamWCg21LcPvg                           Design Diary
224  UC4SY8B841CuWlrcFkH0nA2g                     Game Design Corner
225  UCJWKjrrUh2KL1d3zXQW79cQ                        EXPLORE WITH US
226  UCYwVxWpjeKFWwu8TML-Te9A              JCS - Criminal Psychology
227  UCac1MisHGa0qtzf0oWlU8Zw                          Unpredictable
228  UCa840NC-ZxtMIZ5wYnBcn7w                          Doug Woolever
229  UCPwuva5LbnwFTetkP_cUQHA                             Paper Will
230                      None                                   None
231  UCR6LasBpceuYUhuLToKBzvQ                            Solar Sands
232  UCtGoikgbxP4F3rgI9PldI9g                    Super Eyepatch Wolf
233  UCTWbP-2W-_6mzWLg2oZmT7Q                         RetroGamingNow
234  UCRcgy6GzDeccI7dkbbBna3Q                                LEMMiNO
235  UC-9b7aDP6ZN0coj9-xFnrtw                                 Astrum
236  UCf5POn4NNKIIGmXOu6qhbsQ                          Inside A Mind
237  UC5UYMeKfZbFYnLHzoTJB1xA               Schaffrillas Productions
238  UCDETFHKteb-C_EaXmRKvP4w                            Sisyphus 55
239  UCybBViio_TH_uiFFDJuz5tg                           Einzelgänger
240  UCimiUgDLbi6P17BdaCZpVbg                                exurb1a
241  UCO5QSoES5yn2Dw7YixDYT5Q                               Aperture
242  UC-tLyAaPbRZiYrOJxAGB7dQ                      Pursuit of Wonder
243  UCGSmy2st0rb63fAkoO1aGyw                               IMBeggar
244  UCfNcetb0dXVk53jZ9I0uKnA                 Implicitly Pretentious
245  UCuzWsvCIGy56ELIsKc4MOUQ                              flowstate
246  UCpnyVXM0hAd6BAjSrmZ8GfQ                     The Writer's Block
247  UCtrh0mrPWX2_9i2NJP2xZ6Q                        MakeBetterMedia
248  UCBk1w-2BLkm5L72tc0eI74g                              Simon Kim
249  UCVHxJghKAB_kA_5LMM8MD3w                              oliSUNvia

In [49]:
df = df.drop(rows_to_drop)
df = df.reset_index(drop=True)
df.head()

                 channel_id            channel_name
0  UCqgh7QNlVV8kv3LBTJZYWrg          The Film Essay
1  UCjFqcJQXGZ6T6sxyFB-5i6A  Every Frame a Painting
2  UCr8r7UVsDaRiIQSVUHVBd_A           Nikki Carreon
3  UCjKSoJlPgcK6BmoSqXpj5xQ           Action Button
4  UCUyvQV2JsICeLZP4c_h40kA           Thomas Flight

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 252 entries, 0 to 251
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   channel_id    251 non-null    object
 1   channel_name  251 non-null    object
dtypes: object(2)
memory usage: 4.1+ KB

In [52]:
df.to_json("../data/processed/ve_channels/ve.json")